AWSTemplateFormatVersion: '2010-09-09'
Description: Lamby Site Asset Host

Parameters:
  StageEnv:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod

Mappings:

  Domain:
    staging:
      Name: lamby-assets-staging.custominktech.com
    prod:
      Name: lamby-assets-prod.custominktech.com

Resources:

  AssetHostBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: lamby-assets-${StageEnv}
      Tags:
        - Key: env
          Value: !Ref StageEnv
        - Key: group
          Value: shared
        - Key: application
          Value: lamby

  AssetHostBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetHostBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${AssetHostBucket}/*'
            Principal:
              CanonicalUser: !GetAtt AssetHostDistributionIdentity.S3CanonicalUserId

  AssetHostDistributionIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Ref AssetHostBucket

  AssetHostDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::FindInMap: [ Domain, !Ref 'StageEnv', Name ]
        Comment: !Sub 'lamby-assets-${StageEnv}'
        DefaultCacheBehavior:
          AllowedMethods: [ HEAD, GET ]
          CachedMethods: [ HEAD, GET ]
          Compress: true
          DefaultTTL: 31536000
          MinTTL: 31536000
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt 'AssetHostBucket.DomainName'
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${AssetHostDistributionIdentity}'
        ViewerCertificate:
          AcmCertificateArn: '{{resolve:ssm:/cf/custominktech/certarn:1}}'
          SslSupportMethod: sni-only
      Tags:
        - Key: env
          Value: !Ref StageEnv
        - Key: group
          Value: shared
        - Key: application
          Value: lamby

